### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by Fredrik93**
## Description

* Preventing the app from crashing by adding try/catches and reformatted some button sizes
* Commented unnecessary code. 
* Added all text into strings.xml file 

 ### Pushed but not tested in combination with arduino sketch  ! Don't merge yet ! 

## Related issue(s)
#40

### CODE REVIEW

**Review by DetailsMatterM — APPROVED** [review]
Amazing bugfixes, finally no crashes anymore! Good job Fredrik

**Comment by Fredrik93** [comment]
Why does it say that there is an open pull request on this branch when it has been merged already ? @platisd @Hlebanja

**Comment by platisd** [comment]
To me it looks like it's merged

**Comment by Fredrik93** [comment]
Righto, thanks !

Den mån 20 maj 2019 17:23 skrev Dimitris Platis <notifications@github.com>:

**Pull request merged**
